import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";

import "../globals.css";

const spaceGrotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode;
    params: {
        locale: string;
    };
}>) {
    return (
        <html lang={params.locale}>
            <body className={spaceGrotesk.className}>
                {children}
                <Toaster />
            </body>
        </html>
    );
}
